extract_curriculum_data:
  description: >
     Use the LatexReaderTool and PDFSearchTool to read the curriculum files provided in the inputs ('resume_path').
     If a path points to a `.tex` file, use LatexReaderTool to extract a structured list containing:
     - Professional experiences
     - Skills
     - Academic background
     If a path points to a `.pdf` file, use PDFSearchTool to perform text extraction and then structure the extracted data into the same categories.
  expected_output: >
    A structured dictionary containing:
    - Professional experiences (e.g., job titles, companies, durations, responsibilities)
    - Skills (e.g., technical, soft skills)
    - Academic background (e.g., degrees, institutions, graduation dates)
  inputs:
    - resume_path

analyze_job_description:
  description: >
    Use the WebScraperTool to read the job description from the URL provided in the inputs ('job_url') and extract:
    - Technical requirements
    - Valued experiences
    - Keywords
  expected_output: >
    A bullet-point summary highlighting the key requirements and aspects to emphasize in the resume, based on the job description analysis.
  inputs:
    - job_url

adjust_resume_for_job:
  description: >
    Using the structured resume data from the 'extract_curriculum_data' task and the job analysis summary from the 'analyze_job_description' task as context, rewrite and reorganize sections of the original resume content to improve alignment with the target job.
    Focus on highlighting relevant skills and experiences based *only* on the provided resume content. Do not invent new information or experiences.
    Follow these guidelines:
    - Emphasize content relevant to the job to improve ATS scoring. Avoid complex graphics unless requested.
    - Prioritize skills and qualifications over personal data.
    - Organize information strategically for readability.
    - Set the Objective field to: "Atuar como [job_title]" (where [job_title] is inferred from the job description).
    - Ensure the final resume content is concise, ideally fitting within two pages when compiled.
  expected_output: >
    The complete, modified content of the resume as a single block of LaTeX code, ready to be saved to a `.tex` file.
  context:
    - extract_curriculum_data
    - analyze_job_description
