extract_curriculum_data:
  description: >
    Use the PDF Search tool to read the curriculum PDF file provided in the inputs and extract a structured list containing:
    Use the LatexReaderTool to read the curriculum `.tex` file provided in the inputs ('resume_path') and extract a structured list containing:

    - Professional experiences
    - Skills
    - Academic background
  expected_output: >
    A structured dictionary with the extracted resume data (experiences, skills, education).
  inputs:
    file_path: /Users/georgesouza/Desktop/Python2025/Curriculo/resume_optimizer_crew_v2/input/

analyze_job_description:
  description: >
    Use the WebScraperTool to read the job description from the URL provided in the inputs ('job_url') and extract:
    - Technical requirements
    - Valued experiences
    - Keywords
  expected_output: >
    A bullet-point summary highlighting the key requirements and aspects to emphasize in the resume, based on the job description analysis.

adjust_resume_for_job:
  description: >
    Using the structured resume data from the 'extract_curriculum_data' task and the job analysis summary from the 'analyze_job_description' task as context, rewrite and reorganize sections of the original resume content to improve alignment with the target job.
    Focus on highlighting relevant skills and experiences based *only* on the provided resume content. Do not invent new information or experiences.
    Follow these guidelines:
    - Emphasize content relevant to the job to improve ATS scoring. Avoid complex graphics unless requested.
    - Prioritize skills and qualifications over personal data.
    - Organize information strategically for readability.
    - Set the Objective field to: "Atuar como [job_title]" (where [job_title] is inferred from the job description).
    - Ensure the final resume content is concise, ideally fitting within two pages when compiled.
  expected_output: >
    The complete, modified content of the resume as a single block of LaTeX code, ready to be saved to a `.tex` file.
  context:
    - extract_curriculum_data
    - analyze_job_description
